In [ ]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

1.9.1+cu111


## Introduction to tensors
### Creating tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX.shape


torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[6,7,8]]])
TENSOR.ndim
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [ ]:
# RANDOM TENSORS
# Start with random numbers, look at data, update random numbers, look at data, update random numbers
# Create random tensors, size (3,4)
random_tensor = torch.rand(3,3)
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(3,100,100)


In [ ]:
# zeros and ones
zero = torch.zeros(size=(3,3))
zero.dtype
TENSOR*zero

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
# Create range of tensors (first, last, step0)
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
# create tensors like
ten_zero = torch.ones_like(input=one_to_ten)
ten_zero

tensor([1, 1, 1, 1, 1])

In [ ]:
# tensors data types (one of the 3 big errors)
# wrong data type
# not right shape
# not in right device
float_32_tensor = torch.tensor([[2,1,3]],dtype=torch.float32)
float_32_tensor.dtype

float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor * float_32_tensor

int_tensor = torch.tensor([[2,1,3]],)
float_32_tensor*int_tensor

tensor([[4., 1., 9.]])

In [ ]:
## Getting infroamtion from tensors
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)
float_32_tensor.size()

torch.Size([1, 3])
torch.float32
cpu


torch.Size([1, 3])

In [ ]:
%%time
# Tensor operations: Add, Sub, Mul, Div, Matrix multiplications
# inner dimensions must match for Matrix multiplication
# ouput dimentsions of matrix multiplicaiton is outer dimension
tensor = torch.tensor([[1,2,4],[3,4,5],[6,7,8],[1,2,3]])
torch.mul(tensor,10)
# Transpose for multiplication
torch.matmul(tensor,tensor.T)
tensor @ tensor.T

CPU times: total: 0 ns
Wall time: 999 µs


tensor([[ 21,  31,  52,  17],
        [ 31,  50,  86,  26],
        [ 52,  86, 149,  44],
        [ 17,  26,  44,  14]])

In [ ]:
# Tensor aggregation (min, max, mean, sum)
torch.max(tensor)
torch.mean(tensor.type(torch.float32))


tensor(3.8333)

In [ ]:
# Positional Min & Max
print("Posigion for minimum",torch.argmin(tensor))
print("Posigion for maximum",torch.argmax(tensor))


Posigion for minimum tensor(0)
Posigion for maximum tensor(8)


## Reshaping, stacking, squeezing and unsquezing tensors
* Reshaping: reshapes an input tensor to a defined shape
* view- return a view of an input tensor of certain shape but keeps the same memory as teh original sensor
* Stack> concatenates (verticallly or horizontally)
* squeeze / unsqueeze removes or adds dimensions to a sensor

In [ ]:
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#change the view
x_viewed = x.view(2,5)
x_viewed

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
# Stack tensors
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [ ]:
x_squeeze = torch.unsqueeze(x_stacked, dim=1)
x_squeeze, x_squeeze.size()

(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],
 
         [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],
 
         [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],
 
         [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]]),
 torch.Size([4, 1, 10]))

In [ ]:
#torch.permute, permutes de dimension (used in images)
x = torch.randn(size =(128,128,4)) #  height, width, colour channels
# permute to rearrange the axis
x_permuted = x.permute(2,0,1) # permute *column indexes
print(x_permuted.shape)


torch.Size([4, 128, 128])


In [ ]:
# Indexing (selecting data from tensors)
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][2][2]


tensor(9)

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
# Numpy to Pytorch
# torch.from_numpy(array)
import numpy as np
import torch
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to  Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Reproducibility *tring to take random out of random"
import torch
RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## USING GPU

In [8]:
# CPU vs GPU in CUDA
# 
import torch
print(torch.__version__)
torch.cuda.is_available()

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
NUM_CPU = torch.cuda.device_count()
print(f"total CPUs: {NUM_CPU}")

1.9.1+cu111
cuda
total CPUs: 1
